### ISSUE TITLE
Issue with test suite 012_musiclibrary_cli_spec.rb, spec #1

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/ruby-music-library-cli#25]
For 'it allows a user to list songs,' the expected order of songs in the test suite is: 
1. Action Bronson - Larry Csonka - indie
2. Real Estate - Green Aisles - country
3. Real Estate - It's Real - hip-hop
4. Thundercat - For Love I Come - dance

After passing specs in suites 001-011, I failed suite 012 spec 1 because the order of songs in output was:
1. Thundercat - ...
2. Action Bronson - ...
3. Real Estate - Green Aisles -...
4. Real Estate - It's Real - ..

even though the test files for importing were listed in the spec's order (see screenshot image below: IDE file structure on left shows files in spec order 1, 2, 3, 4; terminal captures rspec failure showing the output order as 4, 1, 2, 3 relative to the file structure).  A Learn Expert confirmed (via ask-a-question) that the solution branch fails its own rspec test because of the order of the songs.  No suggestions for how to resolve, unfortunately.

![image](https://cloud.githubusercontent.com/assets/15614698/18413456/8cc28960-7776-11e6-9012-8dddafe1ceaa.png)

**Comment by AnnJohn** [comment]
thanks for raising @christinalcole 

hi @cjbrock if you have time, could you take a look at this issue. thanks!

**Comment by TheLucasMoore** [comment]
@AnnJohn This should be resolved with #27

**Comment by joshuabamboo** [comment]
Unfortunately, this is still an issue. #27 is not doing the trick because we cannot predict the order of the songs. 

Student's are calling [`Dir.glob`](https://ruby-doc.org/core-2.4.0/Dir.html#method-c-glob) in the `files` method. The problem stems from the return value of `glob`. The order in which the results are returned depends on your system. IE we cannot predict order if students are using `glob`.

Perhaps we should remove the testing of order altogether? @aturkewi

**Comment by aturkewi** [comment]
Thanks for re-raising this @joshuabamboo 

I'll see if I can get some one to fix this. I think the best sol might be to ensure that when some one does `Song.all` it will do something like `@@all.sort` and return songs sorted in a particular way. 

@cjbrock thoughts?
